DROP TABLE IF EXISTS PRICES;

CREATE TABLE PRICES (
  BRAND_ID INT NOT NULL,
  START_DATE TIMESTAMP NOT NULL,
  END_DATE TIMESTAMP NOT NULL,
  PRICE_LIST INT AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_ID INT NOT NULL,
  PRIORITY SMALLINT NOT NULL,
  PRICE DECIMAL(10,2) NOT NULL,
  CURR VARCHAR(3) NOT NULL
);
